
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author World
 */
public class detailPembayaran extends javax.swing.JFrame {

    /**
     * Creates new form detailPembayaran
     */
    public detailPembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uangBayar = new javax.swing.JTextField();
        totalBayar = new javax.swing.JLabel();
        uangDiBayarkan = new javax.swing.JLabel();
        kembalian = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        detailPembayaran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangBayarActionPerformed(evt);
            }
        });
        uangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uangBayarKeyTyped(evt);
            }
        });
        getContentPane().add(uangBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 170, 30));
        getContentPane().add(totalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 160, 40));
        getContentPane().add(uangDiBayarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 170, 30));
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 140, 30));

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnPrint.png"))); // NOI18N
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 80, 30));

        detailPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/detailPbyrn.png"))); // NOI18N
        getContentPane().add(detailPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        new harga().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_printActionPerformed

    private void uangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangBayarActionPerformed

    private void uangBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangBayarKeyTyped
 char uangBayar = evt.getKeyChar();
        if (!(Character.isDigit(uangBayar)
                ||(uangBayar==KeyEvent.VK_BACK_SPACE)
                ||(uangBayar==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "harus diisi angka");
        }
    }//GEN-LAST:event_uangBayarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailPembayaran;
    private javax.swing.JLabel kembalian;
    private javax.swing.JButton print;
    private javax.swing.JLabel totalBayar;
    private javax.swing.JTextField uangBayar;
    private javax.swing.JLabel uangDiBayarkan;
    // End of variables declaration//GEN-END:variables
}
