
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author World
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public logIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passWord = new javax.swing.JPasswordField();
        logIn = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWordKeyPressed(evt);
            }
        });
        getContentPane().add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 270, 30));

        logIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnlogin.png"))); // NOI18N
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        getContentPane().add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 110, 30));

        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameKeyTyped(evt);
            }
        });
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        
        try{
            String userName = this.userName.getText();
           String password = this.passWord.getText();
        if (userName.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "isi nama dulu gan");
        }
        else if (passWord.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "isi password gan");
        }
        
            if (userName.equals("admin") && password.equals("admin")) {
         new harga().setVisible(true);
      this.dispose();
                //misal  
            }
            else if (userName.equals("manager") && password.equals("manager")) {
         new HomeManajer().setVisible(true);
      this.dispose();       
            }
      else {
         JOptionPane.showMessageDialog(this,"username atau password salah");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_logInActionPerformed

    private void userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyTyped
    char userName = evt.getKeyChar();
        if (!(Character.isAlphabetic(userName)
                ||(userName==KeyEvent.VK_BACK_SPACE)
                ||(userName==KeyEvent.VK_DELETE)
                ||(userName==KeyEvent.VK_ENTER)
                )){
            evt.consume();
            JOptionPane.showMessageDialog(this, "harus diisi huruf");
        }
    }//GEN-LAST:event_userNameKeyTyped

    private void passWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordKeyPressed
        if ((evt.getKeyCode()==KeyEvent.VK_ENTER)) {
        try{
            String userName = this.userName.getText();
           String password = this.passWord.getText();
        if (userName.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "isi nama dulu gan");
        }
        else if (passWord.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "isi password gan");
        }
        
            if (userName.equals("admin") && password.equals("admin")) {
         new harga().setVisible(true);
      this.dispose();
                //misal  
            }
            else if (userName.equals("manager") && password.equals("manager")) {
         new HomeManajer().setVisible(true);
      this.dispose();       
            }
      else {
         JOptionPane.showMessageDialog(this,"username atau password salah");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }    
        }
    }//GEN-LAST:event_passWordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logIn;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
