
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author World
 */
public class pesanKasir extends javax.swing.JFrame {

    /**
     * Creates new form pesanKasir
     */
    public pesanKasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenis = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        kuantitas = new javax.swing.JTextField();
        namaPemesan = new javax.swing.JTextField();
        cek = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        namaAdmin = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        tambahPesanan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMIN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        level.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(1)  MERAH MERONA", "(2)  MERAH MENGGODA", "(3)  MERAH MEREKAH", "(4)  MERAH MENYALA", "(5)  MERAH MEMBARA", " " }));
        level.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        kuantitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kuantitasKeyTyped(evt);
            }
        });
        getContentPane().add(kuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 40, -1));

        namaPemesan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaPemesanKeyTyped(evt);
            }
        });
        getContentPane().add(namaPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, -1));

        cek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btncekpsn.png"))); // NOI18N
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });
        getContentPane().add(cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 180, 30));
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));
        getContentPane().add(namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 80, 30));
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 20, 20));

        jenis.add(jRadioButton1);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jenis.add(jRadioButton2);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jenis.add(jRadioButton3);
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        tambahPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn+psn.png"))); // NOI18N
        tambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPesananActionPerformed(evt);
            }
        });
        getContentPane().add(tambahPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inputPsn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        new detailPesanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cekActionPerformed

    private void tambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPesananActionPerformed
        new pesanKasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tambahPesananActionPerformed

    private void namaPemesanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPemesanKeyTyped
char namaPemesan = evt.getKeyChar();
        if (!(Character.isAlphabetic(namaPemesan)
                ||(namaPemesan==KeyEvent.VK_BACK_SPACE)
                ||(namaPemesan==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "harus diisi huruf");
        }
    }//GEN-LAST:event_namaPemesanKeyTyped

    private void kuantitasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kuantitasKeyTyped
 char kuantitas = evt.getKeyChar();
        if (!(Character.isDigit(kuantitas)
                ||(kuantitas==KeyEvent.VK_BACK_SPACE)
                ||(kuantitas==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "harus diisi angka");
        }
    }//GEN-LAST:event_kuantitasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cek;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.ButtonGroup jenis;
    private javax.swing.JTextField kuantitas;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JLabel namaAdmin;
    private javax.swing.JTextField namaPemesan;
    private javax.swing.JButton tambahPesanan;
    // End of variables declaration//GEN-END:variables
}
